### ISSUE TITLE
Is this org.bitcoin.wallet on google-play?

### ISSUE THREAD

**Issue by emanuelb** [bitcoin-dot-org/BitcoinWalletMobile#4]
There is app on google-play: "Bitcoin Wallet: by Bitcoin.org"
https://play.google.com/store/apps/details?id=org.bitcoin.wallet
which use appid `org.bitcoin.wallet` but this repo use appid `com.bitcoinwalletmobile` , the `org.bitcoin.wallet` is used in another repo which is not a mobile wallet?! https://github.com/bitcoin-dot-org/Bitcoin-Wallet/blob/896565580cb1fe162f67bfc59124d8924231e347/vue.config.js#L8 so

So the question is this app in google-play yours? legit? if it's legit please point to it in the README of the repo and also git tag releases/version (so easier to test for reproducibility, etc..)

**Comment by Cobra-Bitcoin** [comment]
Yes, it's legit. I'm currently just testing for issues with live users from the app stores. Still need to do more work on improving this repo, as you suggested. Thanks for the heads up.

**Comment by emanuelb** [comment]
can you point to the commit used to build the 1.0 version on google-play? also it's better to mention the app in google-play in some places like README.md here, as due to missing mentions, no related tag, mismatch in appid, thought that the app in play-store was fake/scam...

**Comment by Cobra-Bitcoin** [comment]
https://github.com/bitcoin-dot-org/BitcoinWalletMobile/releases/tag/v1.0

Yeah, I totally get that, I'll update the README soon to point to the app in the Google/Apple store. It's obviously legit, but we're trying to be lowkey about it for now, we need to make sure users aren't losing money before we promote it more.

**Comment by emanuelb** [comment]
Closing this issue, as I rebuild the app and compared it, so it's legit.
> but we're trying to be lowkey about it for now, we need to make sure users aren't losing money before we promote it more.

for this you might add some warning like "app is currently in BETA state, use with caution, don't store lots of money with it.." to the README and in google-play, so people who download it or compile to use will know...

**Comment by Giszmo** [comment]
Thanks @emanuelb for finding this. I updated walletscrutiny accordingly. Personally I think it's asking for hate and trouble to release an "official" bitcoin.org mobile wallet but the current name "Bitcoin Wallet: by Bitcoin.org" shows clearly that ambition.
